# Generated by Django 3.2 on 2022-09-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_setup_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('authors', models.ManyToManyField(to='postgres_setup_app.Author')),
            ],
        ),
    ]
